.PHONY: test clean

a.out: main.ml
	ocamlfind ocamlopt -package num -linkpkg main.ml

test: a.out
{% for example in examples %}
	@cat {{ example.in_file_name }} | ./a.out > {{ example.out_file_name }}.gen
	diff {{ example.out_file_name }} {{ example.out_file_name }}.gen
{% endfor %}

clean:
	rm -f a.out
	rm -f *.gen
